/**
 * `scaffold pack new --dir <path> --version <version> [--stack <label>]`:
 * scaffolds the smallest real, valid pack skeleton — an empty
 * (targets: [], injections: [], inputs: []) manifest.templates.json under
 * <dir>/<version>/, plus a commented tools/validate-build.mjs stub at
 * <dir>/tools/ (a peer of every version folder, matching every existing
 * pack's layout, e.g. packages/templates-dotnet/tools/validate-build.mjs).
 *
 * Deliberately minimal: no .hbs templates, no test_data fixtures. The empty
 * descriptor passes `scaffold validate-pack` trivially (there's nothing yet
 * to render), and the stub build-check fails loudly until the author
 * replaces it with a real one — an unfinished pack should never look
 * "validated". The author's next step is adding their first target,
 * template, and test_data fixture by hand.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export interface PackNewOptions {
  dir: string;
  version: string;
  stack?: string;
}

export interface PackNewResult {
  descriptorPath: string;
  validateBuildPath: string;
}

/** A broad default range; a real pack narrows this to the CLI features it actually uses (v9-enterprise declares >=0.3.0). */
const SCAFFOLD_CLI_RANGE = '>=0.2.0 <1.0.0';

function buildDescriptor(options: PackNewOptions): Record<string, unknown> {
  return {
    descriptorSchemaVersion: 2,
    packVersion: options.version,
    requires: { scaffoldCli: SCAFFOLD_CLI_RANGE },
    _comment: options.stack
      ? `Skeleton generated by "scaffold pack new" for stack "${options.stack}" — add targets/injections/inputs as this pack grows.`
      : 'Skeleton generated by "scaffold pack new" — add targets/injections/inputs as this pack grows.',
    inputs: [],
    targets: [],
    injections: [],
  };
}

function validateBuildStub(options: PackNewOptions): string {
  const stackNote = options.stack ? `the "${options.stack}"` : 'your';
  return `#!/usr/bin/env node
/**
 * tools/validate-build.mjs — STUB, generated by "scaffold pack new".
 *
 * "scaffold validate-pack" only proves generate doesn't throw; it never
 * catches a compile error in the rendered output. This script is the
 * deeper check every pack in this repo ships: render this pack's
 * test_data/ fixtures through the real "scaffold generate" CLI into a
 * throwaway sample project, then actually build/test that output with
 * ${stackNote} stack's own toolchain — see
 * packages/templates-dotnet/tools/validate-build-v9.mjs in this repo for a
 * worked example to copy from.
 *
 * TODO: add test_data/ fixtures for this pack, then replace this stub with
 * a real build-check.
 */

console.error('tools/validate-build.mjs is a stub — no real build-check implemented yet for this pack.');
process.exit(1);
`;
}

export function createPackSkeleton(options: PackNewOptions): PackNewResult {
  const versionDir = path.join(options.dir, options.version);
  const descriptorPath = path.join(versionDir, 'manifest.templates.json');
  if (existsSync(descriptorPath)) {
    throw new Error(`${descriptorPath} already exists — refusing to overwrite`);
  }

  mkdirSync(versionDir, { recursive: true });
  writeFileSync(descriptorPath, `${JSON.stringify(buildDescriptor(options), null, 2)}\n`, 'utf8');

  const toolsDir = path.join(options.dir, 'tools');
  mkdirSync(toolsDir, { recursive: true });
  const validateBuildPath = path.join(toolsDir, 'validate-build.mjs');
  if (!existsSync(validateBuildPath)) {
    writeFileSync(validateBuildPath, validateBuildStub(options), 'utf8');
  }

  return { descriptorPath, validateBuildPath };
}
